version: "3.4"
services:
  mongo:
    image: mongo
    restart: always

  api:
    build: ./content-api
    image: local-fabrikam-api
    depends_on:
      - mongo
    environment:
      MONGODB_CONNECTION: mongodb://mongo:27017/contentdb    
